services:
  auth:
    image: auth
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./auth.sh
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: